In [1]:
import pandas as pd    ##data handling
import numpy          ##numerical python  in mathematical calc
from sklearn import svm      ## proving us regarding algorithm
from sklearn.linear_model import LogisticRegression

In [2]:
data = pd.read_csv('data_arrhythmia.csv')

In [3]:
data.head()

Age  Sex  Height  Weight  qrs_duration  p-r_interval  q-t_interval  \
0   75    0     190      80            91           193           371   
1   56    1     165      64            81           174           401   
2   54    0     172      95           138           163           386   
3   55    0     175      94           100           202           380   
4   75    0     190      80            88           181           360   

   t_interval  p_interval  qrs  ...   KY    KZ   LA   LB  LC   LD   LE    LF  \
0         174         121  -16  ...  0.0   9.0 -0.9  0.0   0  0.9  2.9  23.3   
1         149          39   25  ...  0.0   8.5  0.0  0.0   0  0.2  2.1  20.4   
2         185         102   96  ...  0.0   9.5 -2.4  0.0   0  0.3  3.4  12.3   
3         179         143   28  ...  0.0  12.2 -2.2  0.0   0  0.4  2.6  34.6   
4         177         103  -16  ...  0.0  13.1 -3.6  0.0   0 -0.1  3.9  25.4   

     LG  diagnosis  
0  49.4          8  
1  38.8          6  
2  49.0         10  
3  61.6          1  
4  62.8          7  

[5 rows x 280 columns]

In [4]:
data["diagnosis"].unique()

array([ 8,  6, 10,  1,  7, 14,  3, 16,  2,  4,  5,  9, 15], dtype=int64)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356 entries, 0 to 1355
Columns: 280 entries, Age to diagnosis
dtypes: float64(121), int64(159)
memory usage: 2.9 MB


In [6]:
data.describe()

Age          Sex       Height       Weight  qrs_duration  \
count  1356.000000  1356.000000  1356.000000  1356.000000   1356.000000   
mean     46.471239     0.550885   166.188053    68.170354     88.920354   
std      16.454474     0.497587    37.142898    16.578554     15.353051   
min       0.000000     0.000000   105.000000     6.000000     55.000000   
25%      36.000000     0.000000   160.000000    59.000000     80.000000   
50%      47.000000     1.000000   164.000000    68.000000     86.000000   
75%      58.000000     1.000000   170.000000    79.000000     94.000000   
max      83.000000     1.000000   780.000000   176.000000    188.000000   

       p-r_interval  q-t_interval   t_interval   p_interval          qrs  ...  \
count   1356.000000   1356.000000  1356.000000  1356.000000  1356.000000  ...   
mean     155.152655    367.207965   169.949115    90.004425    33.676991  ...   
std       44.809176     33.360774    35.606765    25.807576    45.397893  ...   
min        0.000000    232.000000   108.000000     0.000000  -172.000000  ...   
25%      142.000000    350.000000   148.000000    79.000000     3.750000  ...   
50%      157.000000    367.000000   162.000000    91.000000    40.000000  ...   
75%      175.000000    384.000000   179.000000   102.000000    66.000000  ...   
max      524.000000    509.000000   381.000000   205.000000   169.000000  ...   

                KY           KZ           LA           LB      LC  \
count  1356.000000  1356.000000  1356.000000  1356.000000  1356.0   
mean     -0.278982     9.048009    -1.457301     0.003982     0.0   
std       0.548471     3.470298     2.000951     0.050081     0.0   
min      -4.100000     0.000000   -28.600000     0.000000     0.0   
25%      -0.425000     6.600000    -2.100000     0.000000     0.0   
50%       0.000000     8.800000    -1.100000     0.000000     0.0   
75%       0.000000    11.200000     0.000000     0.000000     0.0   
max       0.000000    23.600000     0.000000     0.800000     0.0   

                LD           LE           LF           LG    diagnosis  
count  1356.000000  1356.000000  1356.000000  1356.000000  1356.000000  
mean      0.514823     1.222345    19.326106    29.473230     3.880531  
std       0.347274     1.424999    13.493952    18.480273     4.403843  
min      -0.800000    -6.000000   -44.200000   -38.600000     1.000000  
25%       0.400000     0.500000    11.450000    17.550000     1.000000  
50%       0.500000     1.350000    18.100000    27.900000     1.000000  
75%       0.700000     2.100000    25.825000    41.125000     6.000000  
max       2.400000     6.000000    88.800000   115.900000    16.000000  

[8 rows x 280 columns]

# PRE PROCESSING DATA (Removing Missing & NaN values)

In [7]:
data = data.fillna(data.mean())

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356 entries, 0 to 1355
Columns: 280 entries, Age to diagnosis
dtypes: float64(121), int64(159)
memory usage: 2.9 MB


In [9]:
data.isnull().sum()

Age             0
Sex             0
Height          0
Weight          0
qrs_duration    0
               ..
LD              0
LE              0
LF              0
LG              0
diagnosis       0
Length: 280, dtype: int64

In [10]:
X = data.iloc[:,:-1]
#create feature matrix
#reader=csv.reader(open("feature.csv","r"),delimiter=",")
#X=list(reader)
X=numpy.array(X)
X=X.astype(numpy.float)

y = data.iloc[:,-1]
#create result vector
#reader=csv.reader(open("target_output.csv","r"),delimiter=",")
#y=list(reader)
y=numpy.array(y)
y=y.astype(numpy.int)


C:\Users\Chethana\AppData\Local\Temp\ipykernel_18700\3665311844.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X=X.astype(numpy.float)
C:\Users\Chethana\AppData\Local\Temp\ipykernel_18700\3665311844.py:13: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/releas

In [11]:
#applying random forests to get pricipal attributes
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(X, y.ravel())
#print(model.feature_importances_)

numpy.savetxt("randforrests.csv", model.feature_importances_, fmt='%s', delimiter=",")

#selecting features 
c=0;
important_features=numpy.zeros((278),dtype=numpy.float)
important_features_index=numpy.zeros((278),dtype=numpy.int)

for i in range (0,278):
    if((model.feature_importances_[i]*1000)>=4.5):
        important_features[c]=model.feature_importances_[i]
        important_features_index[c]=i
        c=c+1

print(important_features)
print(important_features_index)
print("The no of features =",c)

#features are reduced  from 278

numpy.savetxt("import_features_index_after_random_forrests.csv",important_features_index, fmt='%s', delimiter=",")

#new matrix compirising of reduced features
newX=numpy.zeros((1356 ,c),dtype=numpy.float)
for i in range (0,1356 ):
    for j in range (0,c):
        newX[i][j]=X[i][important_features_index[j]]


print(newX)

numpy.savetxt("reduced_features.csv",newX, fmt='%s', delimiter=",")

C:\Users\Chethana\AppData\Local\Temp\ipykernel_18700\340371113.py:11: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  important_features=numpy.zeros((278),dtype=numpy.float)
C:\Users\Chethana\AppData\Local\Temp\ipykernel_18700\340371113.py:12: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: h

[0.00599075 0.00701541 0.00459559 0.00572326 0.00920177 0.00485801
 0.00562718 0.00672603 0.00498928 0.00855961 0.00567117 0.01837713
 0.00574043 0.00544499 0.00556493 0.00563573 0.0053688  0.00482474
 0.00563716 0.00508408 0.00579844 0.00639045 0.00451437 0.00547996
 0.00674865 0.0049187  0.00495526 0.00453731 0.004882   0.00692492
 0.02585501 0.0220713  0.00573397 0.00927111 0.01129271 0.0060728
 0.01005804 0.00736567 0.01018557 0.00655944 0.0057905  0.00557548
 0.00613204 0.00532271 0.00481189 0.00613957 0.00661471 0.0063867
 0.00596912 0.01097382 0.00621517 0.0049945  0.00654852 0.00450387
 0.00618345 0.01200889 0.00752817 0.00473192 0.00623156 0.00592336
 0.00674102 0.01153895 0.00527185 0.00471191 0.00619246 0.00514167
 0.00805801 0.00498221 0.0064199  0.004744   0.00480495 0.00494055
 0.00570531 0.01435634 0.00532854 0.00533655 0.00705526 0.00512589
 0.00545781 0.00476768 0.00599988 0.00858554 0.00615461 0.00676932
 0.00516993 0.00672109 0.00653377 0.0061229  0.00646563 0.004650

C:\Users\Chethana\AppData\Local\Temp\ipykernel_18700\340371113.py:29: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  newX=numpy.zeros((1356 ,c),dtype=numpy.float)


[[ 75.    0.  190.  ...   9.    0.9   2.9]
 [ 56.    1.  165.  ...   8.5   0.2   2.1]
 [ 54.    0.  172.  ...   9.5   0.3   3.4]
 ...
 [ 36.    0.  166.  ...  16.3   1.5   1. ]
 [ 32.    1.  155.  ...  12.    0.5   2.4]
 [ 78.    1.  160.  ...  10.4   0.5   1.6]]


In [12]:
x = pd.read_csv('reduced_features.csv')

In [13]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(x,y[:-1],test_size=0.2,random_state=100)

# KNN classifier

In [14]:
from sklearn.neighbors import KNeighborsClassifier
clf_KNN = KNeighborsClassifier(n_neighbors=13)

clf_KNN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [15]:
y_pred_knn  = clf_KNN.predict(X_test)

C:\Users\Chethana\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred_knn,y_test))
score_knn = accuracy_score(y_pred_knn,y_test)

0.5608856088560885
